# Generated by Django 5.1.6 on 2025-04-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50, unique=True)),
                ('filename', models.CharField(max_length=300)),
                ('file_path', models.CharField(max_length=1000)),
                ('thumb_path', models.CharField(max_length=1000)),
                ('license', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateTimeField()),
                ('uploader', models.CharField(max_length=250)),
                ('extension', models.TextField(max_length=10)),
                ('glam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glams.glam')),
            ],
        ),
        migrations.CreateModel(
            name='MediaRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.CharField(choices=[('all-referers', 'All referers'), ('internal', 'Internal'), ('external', 'External'), ('search-engine', 'Search-engine'), ('unknown', 'Unknown'), ('none', 'None')], max_length=50)),
                ('agent', models.CharField(choices=[('all-agents', 'All agents'), ('user', 'Users'), ('spider', 'Spiders')], max_length=50)),
                ('granularity', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=50)),
                ('timestamp', models.CharField(max_length=10)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('wiki', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('page_id', models.CharField(max_length=50)),
                ('namespace', models.CharField(max_length=5)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.mediafile')),
            ],
            options={
                'unique_together': {('file', 'page_id')},
            },
        ),
    ]
