# Generated by Django 5.1.6 on 2025-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediausage',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='mediausage',
            name='url',
            field=models.URLField(max_length=5000),
        ),
    ]
