# Generated by Django 5.1.6 on 2025-04-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_mediausage_title_alter_mediausage_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediarequests',
            unique_together={('file', 'timestamp', 'referer', 'agent', 'granularity')},
        ),
    ]
