# Generated by Django 5.1.6 on 2026-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_alter_mediarequests_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarequests',
            name='agent_new',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mediarequests',
            name='granularity_new',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mediarequests',
            name='referer_new',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mediarequests',
            name='timestamp_new',
            field=models.DateField(null=True),
        ),
    ]
