# Generated by Django 5.1.6 on 2026-04-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_mediarequests_agent_new_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediarequests',
            unique_together={('file', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='mediarequests',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='mediarequests',
            name='agent_new',
        ),
        migrations.RemoveField(
            model_name='mediarequests',
            name='granularity',
        ),
        migrations.RemoveField(
            model_name='mediarequests',
            name='granularity_new',
        ),
        migrations.RemoveField(
            model_name='mediarequests',
            name='referer',
        ),
        migrations.RemoveField(
            model_name='mediarequests',
            name='referer_new',
        ),
    ]
