# Generated by Django 5.1.6 on 2026-04-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_alter_mediarequests_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediarequests',
            old_name='timestamp',
            new_name='timestamp_old',
        ),
        migrations.AlterUniqueTogether(
            name='mediarequests',
            unique_together={('file', 'timestamp_old')},
        ),
    ]
