# Generated by Django 5.1.6 on 2026-04-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_rename_timestamp_mediarequests_timestamp_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediarequests',
            old_name='timestamp_new',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='mediarequests',
            unique_together={('file', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='mediarequests',
            name='timestamp_old',
        ),
    ]
