# Generated by Django 5.1.6 on 2026-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0007_rename_timestamp_new_mediarequests_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarequests',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
